### ISSUE TITLE
Example outdated/broken

### ISSUE THREAD

**Issue by stapelberg** [ninjasphere/go-castv2#1]
In example/main.go, I needed to perform the following fixes to get any output:
1. Replace github.com/armon/mdns with the new name github.com/hashicorp/mdns
2. Remove the `Domain: "local"` line — that value (with a trailing dot, though!) is inferred by the library: https://github.com/hashicorp/mdns/blob/master/zone.go#L77
3. Remove the “.local” from `castService`

Could you please update the example accordingly so that other people don’t have to discover the same issues?

Thanks for your work on this project!

**Comment by elliots** [comment]
G'day @stapleberg. Thanks for the heads-up. 

I've updated it blind as I don't have a ChromeCast available. Would you mind testing it if you get a chance?

**Comment by stapelberg** [comment]
It works for me now. Thanks!
